config/routes.rb
Rails.application.routes.draw do
  get 'users/index' => "users#index", as: :users_index
  get '/' => "users#new", as: :users_new
  get 'users/:id' => "users#show", as: :users_show
  get 'users/:id/edit' => "users#edit", as: :users_edit

  get 'login' => "users#login_form", as: :login_form

  get 'posts/index' => "posts#index", as: :posts_index
  get 'posts/new' => "posts#new", as: :posts_new
  get 'posts/:id' => "posts#show", as: :posts_show
  get 'posts/:id/edit' => "posts#edit", as: :posts_edit

  post 'login' => "users#login", as: :login
  post 'logout' => "users#logout", as: :logout

  post 'users/create' => "users#create", as: :users_create
  patch 'users/:id/update' => "users#update", as: :users_update
  post 'users/:id/destroy' => "users#destroy", as: :users_destroy

  post 'posts/create' => "posts#create", as: :posts_create
  patch 'posts/:id/update' => "posts#update", as: :posts_update
  post 'posts/:id/destroy' => "posts#destroy", as: :posts_destroy
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
    def user
        return User.find_by(id: self.user_id)
    end

    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :posts, dependent: :destroy

    def posts
        return Post.where(user_id: self.id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user

    def set_current_user
        @current_user = User.find_by(id: session[:user_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find_by(id: params[:id])
    @user = @post.user
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def create
    @post = Post.new(create_params)
    @post.save
    redirect_to posts_index_path
  end

  def update
    @post = Post.find_by(id: params[:id])
    @post.update(update_params)
    @post.save
    redirect_to posts_index_path
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    redirect_to posts_index_path
  end

  private

  def create_params
    params.require(:post).permit(:content).merge(user_id: @current_user.id)
  end

  def update_params
    params.require(:post).permit(:content)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def create
    @user = User.new(create_params)
    @user.save
    session[:user_id] = @user.id
    redirect_to users_index_path
  end

  def update
    @user = User.find_by(id: params[:id])
    @user.update(update_params)
    @user.save
    redirect_to users_index_path
  end

  def destroy
    @user = User.find_by(id: params[:id])
    @user.destroy
    redirect_to users_index_path
  end

  def login_form
  end

  def login
    @user = User.find_by(email: params[:user][:email])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to users_index_path
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to login_form_path
  end

  private

  def create_params
    params.require(:user).permit(:name, :email, :password)
  end

  def update_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if @current_user %>
      <%= @current_user.name %>
      <%= link_to "投稿一覧", posts_index_path %>
      <%= link_to "新規投稿", posts_new_path %>
      <%= link_to "ユーザー一覧", users_index_path %>
      <%= button_to "ログアウト", logout_path %>
    <% else %>
      <%= link_to "新規登録", users_new_path %>
      <%= link_to "ログイン", login_form_path %>
    <% end %>
      <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>編集画面</h1>
<%= form_with model: @post, url: posts_update_path do |f| %>
    <label for="content">content</label>
    <%= f.text_field :content %>

    <%= f.submit :更新 %>
<% end %>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>
<% @posts.each do |post| %>
    <%= link_to post.content, posts_show_path(post) %>
<% end %>

app/views/posts/new.html.erb
<h1>新規投稿</h1>
<%= form_with model: @post, url: posts_create_path do |f| %>
    <label for="content">content</label>
    <%= f.text_field :content %>

    <%= f.submit :投稿 %>
<% end %>

app/views/posts/show.html.erb
<h1>投稿詳細</h1>
<%= @user.name %>
<%= @post.content %>
<%= link_to "編集", posts_edit_path %>
<%= button_to "削除", posts_destroy_path %>

app/views/users/edit.html.erb
<h1>編集</h1>
<%= form_with model: @user, url: users_update_path do |f| %>
    <label for="name">name</label>
    <%= f.text_field :name %>

    <label for="email">email</label>
    <%= f.text_field :email %>

    <label for="password">password</label>
    <%= f.text_field :password, type: "password" %>

    <%= f.submit :更新 %>
<% end %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<% @users.each do |user| %>
    <%= link_to user.name, users_show_path(user) %>
<% end %>

app/views/users/login_form.html.erb
<h1>ログイン画面</h1>
<%= form_with model: User.new, url: login_path do |f| %>
    <label for="name">name</label>
    <%= f.text_field :name %>

    <label for="email">email</label>
    <%= f.text_field :email %>

    <label for="password">password</label>
    <%= f.text_field :password, type: "password" %>

    <%= f.submit :ログイン %>
<% end %>

app/views/users/new.html.erb
<h1>新規登録</h1>
<%= form_with model: @user, url: users_create_path do |f| %>
    <label for="name">name</label>
    <%= f.text_field :name %>

    <label for="email">email</label>
    <%= f.text_field :email %>

    <label for="password">password</label>
    <%= f.text_field :password %>

    <%= f.submit :登録 %>
<% end %>

app/views/users/show.html.erb
<h1>ユーザー詳細</h1>
<%= @user.email %>
<%= link_to "編集", users_edit_path %>
<%= button_to "削除", users_destroy_path %>

<% @user.posts.each do |post| %>
    <%= post.content %>
<% end %>